-- 利息计算历史表
CREATE TABLE IF NOT EXISTS `admin_lixijs_history` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `case_no` varchar(100) NOT NULL DEFAULT '' COMMENT '案号',
  `parties` varchar(200) NOT NULL DEFAULT '' COMMENT '当事人',
  `principal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本金',
  `rate` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '利率',
  `rate_type` varchar(20) NOT NULL DEFAULT 'year' COMMENT '利率类型：year/month/day',
  `calc_type` varchar(20) NOT NULL DEFAULT 'simple' COMMENT '计算方式：simple-单利 compound-复利',
  `start_date` date DEFAULT NULL COMMENT '起息日期',
  `end_date` date DEFAULT NULL COMMENT '截止日期',
  `judgment_date` date DEFAULT NULL COMMENT '判决生效日期',
  `due_date` date DEFAULT NULL COMMENT '履行期间届满日',
  `calc_delay_interest` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否计算迟延履行利息：0-否 1-是',
  `days` int(11) NOT NULL DEFAULT '0' COMMENT '计息天数',
  `normal_interest` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '一般债务利息',
  `delay_interest` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '迟延履行利息',
  `delay_days` int(11) NOT NULL DEFAULT '0' COMMENT '迟延天数',
  `total_repayment` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '还款总额',
  `remaining_principal` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '剩余本金',
  `total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应付总额',
  `repayment_list` text COMMENT '还款记录JSON',
  `details` text COMMENT '计算详情JSON',
  `create_by` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_create_by` (`create_by`),
  KEY `idx_case_no` (`case_no`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='利息计算历史表';
